"""Initial schema — all alpha aggregates (data-models.md).

Handwritten rather than autogenerated so the enum types, partial unique index
and CHECK constraint are explicit and reviewable.

Notes:
  * `gen_random_uuid()` is built into PostgreSQL 13+; no pgcrypto extension is
    created.
  * pgvector is deliberately NOT enabled (data-models.md 3). The reserved
    `experiment_run.embedding` column is plain BYTEA until the Phase 2+
    semantic-search feature is actually scheduled.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-01
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())
TS = sa.DateTime(timezone=True)

provider_type = postgresql.ENUM(
    "openai", "anthropic", "gemini", "groq", "mistral", "cohere", "openrouter",
    "azure_openai", "aws_bedrock", "ollama", "vllm",
    name="provider_type",
)
health_status = postgresql.ENUM(
    "healthy", "degraded", "down", "unknown", name="health_status"
)
deployment_backend = postgresql.ENUM("ollama", "vllm", name="deployment_backend")
deployment_status = postgresql.ENUM(
    "pending", "downloading", "running", "stopped", "error", name="deployment_status"
)
routing_strategy = postgresql.ENUM(
    "cheapest", "fastest", "fallback", "round_robin", "weighted",
    "cost_threshold", "latency_threshold",
    name="routing_strategy",
)
request_status = postgresql.ENUM("success", "error", "timeout", name="request_status")
dataset_format = postgresql.ENUM("csv", "json", name="dataset_format")
run_status = postgresql.ENUM(
    "pending", "running", "complete", "failed", name="run_status"
)
item_status = postgresql.ENUM(
    "pending", "running", "complete", "failed", name="item_status"
)
metric_source = postgresql.ENUM(
    "ragas", "deepeval", "promptfoo", "computed", "llm_judge", "human",
    name="metric_source",
)

_ENUMS = (
    provider_type, health_status, deployment_backend, deployment_status,
    routing_strategy, request_status, dataset_format, run_status, item_status,
    metric_source,
)


def _id() -> sa.Column:
    return sa.Column(
        "id", UUID, primary_key=True, server_default=sa.text("gen_random_uuid()")
    )


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", TS, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", TS, server_default=sa.func.now(), nullable=False),
    ]


def _create_enum(bind, enum):
    """Create a PostgreSQL ENUM type idempotently (checkfirst is unreliable with asyncpg)."""
    from sqlalchemy import text
    values = ", ".join(f"'{v}'" for v in enum.enums)
    bind.execute(text(
        f"DO $$ BEGIN "
        f"CREATE TYPE {enum.name} AS ENUM ({values}); "
        f"EXCEPTION WHEN duplicate_object THEN NULL; "
        f"END $$"
    ))


def upgrade() -> None:
    bind = op.get_bind()
    for enum in _ENUMS:
        _create_enum(bind, enum)

    # ---- tenancy --------------------------------------------------------
    op.create_table(
        "organization",
        _id(),
        sa.Column("name", sa.String(200), nullable=False),
        *_timestamps(),
    )
    op.create_index("ix_organization_created_at", "organization", ["created_at"])

    op.create_table(
        "project",
        _id(),
        sa.Column(
            "organization_id",
            UUID,
            sa.ForeignKey("organization.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False, unique=True),
        sa.Column("description", sa.Text(), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_project_organization_id", "project", ["organization_id"])
    op.create_index("ix_project_created_at", "project", ["created_at"])

    op.create_table(
        "api_key",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("key_prefix", sa.String(16), nullable=False),
        sa.Column("key_hash", sa.String(255), nullable=False),
        sa.Column("scopes", JSONB, nullable=False, server_default="[]"),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=True),
        sa.Column("quota_monthly_usd", sa.Numeric(12, 4), nullable=True),
        sa.Column("revoked_at", TS, nullable=True),
        sa.Column("last_used_at", TS, nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_api_key_project_id", "api_key", ["project_id"])
    op.create_index("ix_api_key_key_prefix", "api_key", ["key_prefix"])
    op.create_index("ix_api_key_project_prefix", "api_key", ["project_id", "key_prefix"])
    op.create_index("ix_api_key_created_at", "api_key", ["created_at"])

    # ---- providers ------------------------------------------------------
    op.create_table(
        "provider",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider_type", provider_type, nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("credentials_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("base_url", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "health_status", health_status, nullable=False, server_default="unknown"
        ),
        sa.Column("last_health_check_at", TS, nullable=True),
        sa.Column("last_latency_ms", sa.Integer(), nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("project_id", "display_name", name="uq_provider_project_name"),
    )
    op.create_index("ix_provider_project_id", "provider", ["project_id"])
    op.create_index("ix_provider_created_at", "provider", ["created_at"])

    op.create_table(
        "provider_model",
        _id(),
        sa.Column(
            "provider_id",
            UUID,
            sa.ForeignKey("provider.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(200), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("input_price_per_1m", sa.Numeric(12, 6), nullable=True),
        sa.Column("output_price_per_1m", sa.Numeric(12, 6), nullable=True),
        sa.Column("capabilities", JSONB, nullable=False, server_default="[]"),
        sa.Column("is_available", sa.Boolean(), nullable=False, server_default="true"),
        *_timestamps(),
        sa.UniqueConstraint("provider_id", "model_id", name="uq_provider_model_model_id"),
    )
    op.create_index("ix_provider_model_provider_id", "provider_model", ["provider_id"])
    op.create_index("ix_provider_model_model_id", "provider_model", ["model_id"])
    op.create_index("ix_provider_model_created_at", "provider_model", ["created_at"])

    # ---- deployments ----------------------------------------------------
    op.create_table(
        "deployment",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "provider_id",
            UUID,
            sa.ForeignKey("provider.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("backend_type", deployment_backend, nullable=False),
        sa.Column("model_ref", sa.String(300), nullable=False),
        sa.Column("container_id", sa.String(80), nullable=True),
        sa.Column(
            "status", deployment_status, nullable=False, server_default="pending"
        ),
        sa.Column("gpu_index", sa.Integer(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("download_progress_pct", sa.Integer(), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_deployment_project_id", "deployment", ["project_id"])
    op.create_index("ix_deployment_provider_id", "deployment", ["provider_id"])
    op.create_index("ix_deployment_status", "deployment", ["status"])
    op.create_index("ix_deployment_created_at", "deployment", ["created_at"])

    op.create_table(
        "gpu_sample",
        _id(),
        sa.Column(
            "deployment_id",
            UUID,
            sa.ForeignKey("deployment.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("sampled_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("gpu_util_pct", sa.Float(), nullable=False),
        sa.Column("vram_used_mb", sa.Integer(), nullable=False),
        sa.Column("vram_total_mb", sa.Integer(), nullable=False),
        sa.Column("cpu_util_pct", sa.Float(), nullable=True),
        sa.Column("ram_used_mb", sa.Integer(), nullable=True),
    )
    op.create_index("ix_gpu_sample_sampled_at_desc", "gpu_sample", ["sampled_at"])
    op.create_index(
        "ix_gpu_sample_deployment_sampled", "gpu_sample", ["deployment_id", "sampled_at"]
    )

    # ---- routing --------------------------------------------------------
    op.create_table(
        "routing_policy",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("strategy", routing_strategy, nullable=False),
        sa.Column("config", JSONB, nullable=False, server_default="{}"),
        sa.Column("model_allowlist", JSONB, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="false"),
        *_timestamps(),
        sa.UniqueConstraint("project_id", "name", name="uq_routing_policy_project_name"),
    )
    op.create_index("ix_routing_policy_project_id", "routing_policy", ["project_id"])
    op.create_index("ix_routing_policy_created_at", "routing_policy", ["created_at"])
    # Exactly one active policy per project — enforced by the database, not
    # only by application code.
    op.create_index(
        "uq_routing_policy_one_active_per_project",
        "routing_policy",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )

    # ---- requests -------------------------------------------------------
    op.create_table(
        "request",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "api_key_id", UUID, sa.ForeignKey("api_key.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "routing_policy_id",
            UUID,
            sa.ForeignKey("routing_policy.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "provider_id", UUID, sa.ForeignKey("provider.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("model_id", sa.String(200), nullable=False),
        sa.Column("status", request_status, nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Numeric(14, 8), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(64), nullable=True),
        sa.Column("tags", JSONB, nullable=False, server_default="[]"),
        sa.Column("event_id", sa.String(64), nullable=True),
        sa.Column("requested_at", TS, nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_request_project_id", "request", ["project_id"])
    op.create_index("ix_request_requested_at", "request", ["requested_at"])
    op.create_index(
        "ix_request_project_requested_at", "request", ["project_id", "requested_at"]
    )
    op.create_index("ix_request_project_model", "request", ["project_id", "model_id"])
    op.create_index("ix_request_trace_id", "request", ["trace_id"])
    # Idempotency for at-least-once Redis Stream delivery (ADR-004).
    op.create_index("uq_request_event_id", "request", ["event_id"], unique=True)

    # ---- prompts --------------------------------------------------------
    op.create_table(
        "prompt",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("project_id", "name", name="uq_prompt_project_name"),
    )
    op.create_index("ix_prompt_project_id", "prompt", ["project_id"])
    op.create_index("ix_prompt_created_at", "prompt", ["created_at"])

    op.create_table(
        "prompt_version",
        _id(),
        sa.Column(
            "prompt_id",
            UUID,
            sa.ForeignKey("prompt.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("variables", JSONB, nullable=False, server_default="[]"),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("created_by_note", sa.Text(), nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("prompt_id", "version_number", name="uq_prompt_version_number"),
    )
    op.create_index("ix_prompt_version_prompt_id", "prompt_version", ["prompt_id"])
    op.create_index("ix_prompt_version_created_at", "prompt_version", ["created_at"])

    # ---- experiments ----------------------------------------------------
    op.create_table(
        "experiment",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", JSONB, nullable=False, server_default="[]"),
        *_timestamps(),
    )
    op.create_index("ix_experiment_project_id", "experiment", ["project_id"])
    op.create_index("ix_experiment_name", "experiment", ["name"])
    op.create_index("ix_experiment_created_at", "experiment", ["created_at"])

    op.create_table(
        "experiment_run",
        _id(),
        sa.Column(
            "experiment_id",
            UUID,
            sa.ForeignKey("experiment.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "prompt_version_id",
            UUID,
            sa.ForeignKey("prompt_version.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "provider_model_id",
            UUID,
            sa.ForeignKey("provider_model.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column(
            "request_id", UUID, sa.ForeignKey("request.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("response_text", sa.Text(), nullable=True),
        # Reserved for Phase 2+ semantic search. NOT a pgvector column —
        # the extension is intentionally not enabled in alpha.
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_experiment_run_experiment_id", "experiment_run", ["experiment_id"])
    op.create_index(
        "ix_experiment_run_provider_model_id", "experiment_run", ["provider_model_id"]
    )
    op.create_index("ix_experiment_run_created_at", "experiment_run", ["created_at"])

    # ---- benchmarks -----------------------------------------------------
    op.create_table(
        "benchmark_dataset",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("source_format", dataset_format, nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(1000), nullable=False),
        sa.Column("columns", JSONB, nullable=False, server_default="[]"),
        *_timestamps(),
    )
    op.create_index("ix_benchmark_dataset_project_id", "benchmark_dataset", ["project_id"])
    op.create_index("ix_benchmark_dataset_created_at", "benchmark_dataset", ["created_at"])

    op.create_table(
        "benchmark_run",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "dataset_id",
            UUID,
            sa.ForeignKey("benchmark_dataset.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("prompt_version_ids", JSONB, nullable=False, server_default="[]"),
        sa.Column("provider_model_ids", JSONB, nullable=False, server_default="[]"),
        sa.Column("temperatures", JSONB, nullable=False, server_default="[]"),
        sa.Column("metrics", JSONB, nullable=False, server_default="[]"),
        sa.Column("judge_model_id", sa.String(200), nullable=True),
        sa.Column("status", run_status, nullable=False, server_default="pending"),
        sa.Column("total_items", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completed_items", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(80), nullable=True),
        sa.Column("started_at", TS, nullable=True),
        sa.Column("completed_at", TS, nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_benchmark_run_project_id", "benchmark_run", ["project_id"])
    op.create_index("ix_benchmark_run_dataset_id", "benchmark_run", ["dataset_id"])
    op.create_index("ix_benchmark_run_status", "benchmark_run", ["status"])
    op.create_index("ix_benchmark_run_created_at", "benchmark_run", ["created_at"])

    op.create_table(
        "benchmark_run_item",
        _id(),
        sa.Column(
            "benchmark_run_id",
            UUID,
            sa.ForeignKey("benchmark_run.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("dataset_row_index", sa.Integer(), nullable=False),
        sa.Column(
            "prompt_version_id",
            UUID,
            sa.ForeignKey("prompt_version.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column(
            "provider_model_id",
            UUID,
            sa.ForeignKey("provider_model.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column(
            "request_id", UUID, sa.ForeignKey("request.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("status", item_status, nullable=False, server_default="pending"),
        sa.Column("error_message", sa.Text(), nullable=True),
        *_timestamps(),
    )
    op.create_index(
        "ix_benchmark_run_item_benchmark_run_id", "benchmark_run_item", ["benchmark_run_id"]
    )
    op.create_index(
        "ix_benchmark_run_item_provider_model_id",
        "benchmark_run_item",
        ["provider_model_id"],
    )
    op.create_index(
        "ix_benchmark_run_item_run_status",
        "benchmark_run_item",
        ["benchmark_run_id", "status"],
    )
    op.create_index("ix_benchmark_run_item_created_at", "benchmark_run_item", ["created_at"])

    # ---- evaluation -----------------------------------------------------
    op.create_table(
        "evaluation_result",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "experiment_run_id",
            UUID,
            sa.ForeignKey("experiment_run.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "benchmark_run_item_id",
            UUID,
            sa.ForeignKey("benchmark_run_item.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("metric_name", sa.String(100), nullable=False),
        sa.Column("metric_source", metric_source, nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("metadata", JSONB, nullable=True),
        *_timestamps(),
        # Exactly one parent: an evaluation result belongs to an experiment run
        # XOR a benchmark run item, never both and never neither.
        sa.CheckConstraint(
            "(experiment_run_id IS NULL) <> (benchmark_run_item_id IS NULL)",
            name="ck_evaluation_result_exactly_one_parent",
        ),
    )
    op.create_index("ix_evaluation_result_project_id", "evaluation_result", ["project_id"])
    op.create_index(
        "ix_evaluation_result_experiment_run_id", "evaluation_result", ["experiment_run_id"]
    )
    op.create_index(
        "ix_evaluation_result_benchmark_run_item_id",
        "evaluation_result",
        ["benchmark_run_item_id"],
    )
    op.create_index(
        "ix_evaluation_result_metric", "evaluation_result", ["metric_name", "value"]
    )
    op.create_index(
        "ix_evaluation_result_project_metric",
        "evaluation_result",
        ["project_id", "metric_name"],
    )
    op.create_index("ix_evaluation_result_created_at", "evaluation_result", ["created_at"])

    # ---- playground -----------------------------------------------------
    op.create_table(
        "playground_comparison",
        _id(),
        sa.Column(
            "project_id",
            UUID,
            sa.ForeignKey("project.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        *_timestamps(),
    )
    op.create_index(
        "ix_playground_comparison_project_id", "playground_comparison", ["project_id"]
    )
    op.create_index(
        "ix_playground_comparison_created_at", "playground_comparison", ["created_at"]
    )

    op.create_table(
        "playground_response",
        _id(),
        sa.Column(
            "comparison_id",
            UUID,
            sa.ForeignKey("playground_comparison.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "provider_model_id",
            UUID,
            sa.ForeignKey("provider_model.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column(
            "request_id", UUID, sa.ForeignKey("request.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(14, 8), nullable=True),
        sa.Column("user_vote", sa.Boolean(), nullable=True),
        sa.Column("judge_score", sa.Float(), nullable=True),
        *_timestamps(),
    )
    op.create_index(
        "ix_playground_response_comparison_id", "playground_response", ["comparison_id"]
    )
    op.create_index(
        "ix_playground_response_created_at", "playground_response", ["created_at"]
    )


def downgrade() -> None:
    for table in (
        "playground_response",
        "playground_comparison",
        "evaluation_result",
        "benchmark_run_item",
        "benchmark_run",
        "benchmark_dataset",
        "experiment_run",
        "experiment",
        "prompt_version",
        "prompt",
        "request",
        "routing_policy",
        "gpu_sample",
        "deployment",
        "provider_model",
        "provider",
        "api_key",
        "project",
        "organization",
    ):
        op.drop_table(table)

    bind = op.get_bind()
    for enum in _ENUMS:
        enum.drop(bind, checkfirst=True)
